name = "flowsupply"
main = "src/worker.ts"
compatibility_date = "2026-05-04"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"
binding = "ASSETS"

[vars]
API_WORKER_URL = "https://flowsupply-api.alexander-van-puyenbroeck15.workers.dev"
